### ISSUE TITLE
Assign roles to organization with bulk

### ISSUE THREAD

**Issue by thesardorbroo** [p2-inc/phasetwo-java#11]
Hi everyone👋🏻 I have question. Has SDK assign roles to organization with bulk function or create roles with bulk function? If not, can I implement it?)

Thanks for response😃

**Comment by xgp** [comment]
Not yet, as that PR was just merged yesterday. There are also a couple of recent changes that haven't made it into the [`openapi.yaml` ](https://github.com/p2-inc/phasetwo-docs/blob/main/openapi.yaml) file yet (resend invites, invite attributes, get invite by id, idp link etc.) that need to be updated.

However, if you need to build it for those changes, here are my rough notes on how I do it:

```
1.
docker run --rm --user $(id -u):$(id -g) -v $PWD:/local openapitools/openapi-generator-cli generate -i /local/openapi.yaml -g jaxrs-spec -o /local/java-sdk  --additional-properties=groupId=io.phasetwo,artifactId=phasetwo-admin-client,apiPackage=io.phasetwo.client.openapi.api,modelPackage=io.phasetwo.client.openapi.model,useSwaggerAnnotations=false,useBeanValidation=false,useTags=true,interfaceOnly=true,useJakartaEe=true,hideGenerationTimestamp=true

2.
cp java-sdk/src/gen/java/io/phasetwo/client/openapi/*.java phasetwo-java/src/gen/java/io/phasetwo/client/openapi/
cp java-sdk/src/gen/java/io/phasetwo/client/openapi/api/*.java phasetwo-java/src/gen/java/io/phasetwo/client/openapi/api/
cp java-sdk/src/gen/java/io/phasetwo/client/openapi/model/*.java phasetwo-java/src/gen/java/io/phasetwo/client/openapi/model/
cp java-sdk/src/main/openapi/openapi.yaml phasetwo-java/src/main/openapi/openapi.yaml
cd phasetwo-java/
git diff

3.
#resolve all of the Response issues

4. push a pr and merge to main. auto releases using `.github/workflows/release.yml`

```

**Comment by xgp** [comment]
I added these and released in `0.1.7`

**Comment by thesardorbroo** [comment]
What do you think about get users with their roles in one request?

Now, If I have 10 users then I have to send 10 request for fetching their roles. I think would be better if can get with 1 request

**Comment by xgp** [comment]
I have no opinion. Happy to look at a PR if it’s something you need and would like to see integrated.
