### ISSUE TITLE
how to prevent admin account being autogenerated for each organisation

### ISSUE THREAD

**Issue by MIJohnson** [p2-inc/phasetwo-java#12]
I am creating Organisations through the java client

```
 // Create an Organisation
        OrganizationRepresentation org 
            = new OrganizationRepresentation()
                .name( organisation.identifier )
                .displayName( organisation.label )

        String orgId = phaseTwo.organizations( realm ).create( org )
```

each one results in an unique admin account being autogenerated in the format:
org-admin-23cad518-3115-4a06-8f42-0b847c664c2d@noreply.phasetwo.io

Can I prevent these being auto-created?

**Comment by xgp** [comment]
Not currently. We build that as a sort of organization "service account" that gets used in things like the IdP wizard and admin portal. We'd entertain a PR to disable it, if you want to change it. 

The code that does it is in this method: https://github.com/p2-inc/keycloak-orgs/blob/main/src/main/java/io/phasetwo/service/resource/OrganizationResourceProviderFactory.java#L179

And the code that initiates that `OrganizationCreationEvent` is here: https://github.com/p2-inc/keycloak-orgs/blob/main/src/main/java/io/phasetwo/service/model/jpa/JpaOrganizationProvider.java#L58
