### ISSUE TITLE
If Keycloak is configured without /auth in url, the api always return 404

### ISSUE THREAD

**Issue by sbiermann** [p2-inc/phasetwo-java#8]
Hi,
my Keycloak ist configured that it doesn't uses the "/auth" in the url. But your API add the /auth path to the url, so everytime it produces an http status 404 error when it is called to get for example the list of organizations. The problem is here https://github.com/p2-inc/phasetwo-java/blob/c91fa7a9d6070c9a7450354b2196bcd07888cb56/src/main/java/io/phasetwo/client/PhaseTwo.java#L29

Here is a little example to reproduce it:
        
        String serverUrl = "https://auth.example.com";
        String realm = "my-realm";

        Keycloak keycloak = KeycloakBuilder.builder()
                .serverUrl(serverUrl)
                .realm(realm)
                .grantType(OAuth2Constants.CLIENT_CREDENTIALS)
                .clientId("my-client")
                .clientSecret("secret")
                .build();

        PhaseTwo phaseTwo = new PhaseTwo(keycloak, serverUrl);
        List<OrganizationRepresentation> organizationRepresentations = phaseTwo.organizations(realm).get();

The url should be like https://auth.example.com/realms/my-realm/orgs but it is https://auth.example.com/auth/realms/my-realm/orgs

Kind regards
Stefan

**Comment by xgp** [comment]
@sbiermann Thanks for the detailed report. Looks like we need to pass in the equivalent of whatever keycloak has configured for `KC_HTTP_RELATIVE_PATH` and then use that to build what is now the `APPLICATION_PATH`.

**Comment by sbiermann** [comment]
@xgp Your welcome, any timeline for this issue? As workarround i can implement my own "PhaseTwo" Class, but if the fix will done in a few days, i can wait for it.

**Comment by xgp** [comment]
@sbiermann Please feel free to PR it if you get to it soon. We can probably release a fix sometime next week.
